### ISSUE TITLE
Router is ignoring footways

### ISSUE THREAD

**Issue by janikkaden** [motis-project/ppr#25]
The router is ignoring footpaths, when the start or stop is at a specific node. A direct line (over the grass) is used instead.

The used node is: https://www.openstreetmap.org/node/4924350039 . If this point is changed just a bit, the routing snaps into the correct path. When the position of this node is entered again, it again uses the wrong path.

I could not find another example of this behavior.

**Used data:**
start: 50.810926, 12.9241166
stop: 50.81130895, 12.9244202

**Version:**
Docker image ppr:edge

**Video:**

https://user-images.githubusercontent.com/50618489/229519592-f70deb1b-f9a4-46e9-bc21-0bd29f0a2d67.mov

**Comment by pablohoch** [comment]
I've found the bug and am working on a fix. It's not related to the compiler or mimalloc.

**Comment by janikkaden** [comment]
Thank you Pablo for the explanation and the fast solving of the issue.

I can confirm, that it is now working correctly :)
